[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'b4b4r07/vim-shellutils'

[[plugins]]
repo = 'b4b4r07/vim-shellutils'

[[plugins]]
repo = 'b4b4r07/mru.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'junegunn/vim-emoji'

[[plugins]]
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'lambdalisue/vim-gita'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'AndrewRadev/gapply.vim'

[[plugins]]
repo = 'b4b4r07/solarized.vim'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'b4b4r07/enhancd'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'vim-scripts/mru.vim'

[[plugins]]
repo = 'b4b4r07/vim-sqlfmt'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-scripts/buftabs'

[[plugins]]
repo = 'b4b4r07/vim-buftabs'

[[plugins]]
repo ='vim-syntastic/syntastic'
