name: CI

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install required packages
      run: apt-get update && apt-get install -y git make wget sudo
    - name: Install dotfiles
      run: |
        echo starting dotfiles install
        cd dotfile
        make init
        echo complete dotfiles installation
